### ISSUE TITLE
create an index.html file where users can play with functions provided in the library.

### ISSUE THREAD

**Issue by 0-harshit-0** [0-harshit-0/Utility-HTML5Canvas#1]
Note: If you can't complete it, due to some reason. Just provide the incomplete code, **It will help.**<br>

**Comment by dschimtz** [comment]
Hi, could this issue be assigned to me?

**Comment by 0-harshit-0** [comment]
sure, go for it.

**Comment by 0-harshit-0** [comment]
> 
> 
> Hi, could this issue be assigned to me?
